### ISSUE TITLE
Error executing query when user predicate.and() with multi-item array

### ISSUE THREAD

**Issue by stevebroshar** [Breeze/breeze.js#92]
For an array of predicate object called predicate_Items, this creates a predicate that is the logical AND of them all:

```
if (predicate_Items.length) {
    var predicate = predicate_Items[0];
    if (predicate_Items.length > 1)
        predicate = predicate.and(predicate_Items.slice(1));
}
```
When the number of items is 1 or 2, this works fine.  But when the number of items is 3 or more, then I get this error:

```
TypeError: Cannot read property 'operator' of undefined
    at createPredicateFromArray (.../Scripts/Lib/Breeze/breeze.js:9991:14)
    at createPredicateFromArray (.../Scripts/Lib/Breeze/breeze.js:9995:21)
    at ctor (.../Scripts/Lib/Breeze/breeze.js:9712:20)
    at ctor (.../Scripts/Lib/Breeze/breeze.js:9710:20)
    at proto.and (.../Scripts/Lib/Breeze/breeze.js:9855:18)
    at setupQuery (.../Scripts/Spec.js:34:31)
    at executeQuery (.../Scripts/Spec.js:71:13)
    at Object.<anonymous> (.../Scripts/Spec.js:105:22)
```
Although I didn't try it, I would think this would fail:

```
var p1 = new Predicate('p', 'eq', 0);
var p2 = new Predicate('p', 'eq', 0);
var p3 = new Predicate('p', 'eq', 0);
var p = p1.and([p2, p3]);
var q = new EntityQuery...where(p);
em.executeQuery(q);
```

**Comment by wardbell** [comment]
This bug was reported in [issue #86](https://github.com/Breeze/breeze.js/issues/86) and has been fixed. The fix is scheduled for release in v.1.5.4
